#!/bin/bash

#load xresources
xrdb -merge $HOME/.config/X11/xresources


#bind and remap keys
xbindkeys -f ~/.config/xbindkeys/config
remap_keys
ksp_alt_check &

xrandr --setprovideroutputsource -0x1ff NVIDIA-0
xrandr --auto

#set wallpaper
xwallpaper --zoom ~/desktop/img/walls/wall.png
#xsetroot -solid '#000000'

check_bat &
dunst &

#exec awesome



dwmblocks &
picom &
dwm &
exec sleeper
