#!/bin/bash

#load xresources
xrdb -merge $HOME/.config/X11/xresources


#bind and remap keys
#xbindkeys -f ~/.config/xbindkeys/config
xmodmap ~/.config/X11/xmodmap
remap_keys
ksp_alt_check &
$HOME/.scripts/monitor/hdmi_poll &

xrandr --setprovideroutputsource -0x1ff NVIDIA-0
xrandr --auto
xrandr --output HDMI-0 --left-of eDP-1-0

#set wallpaper
xwallpaper --zoom ~/desktop/img/walls/wall.png
#xsetroot -solid '#000000'

check_bat &

#execute sxhkd with common keybinds and wm-specific keybinds
sxhkd -c "$XDG_CONFIG_HOME/sxhkd/common.sxhkdrc" "$([[ -f "$XDG_CONFIG_HOME/sxhkd/$WM.sxhkdrc" ]] && echo "$XDG_CONFIG_HOME/sxhkd/$WM.sxhkdrc")" &

#start window manager
exec $WM


#dwmblocks &
#dwm &
#exec sleeper
