theme = "nord"

[editor]
line-number = "relative"
color-modes = true
true-color = true
bufferline = "multiple"
auto-format = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
# character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.file-picker]
hidden = false
git-ignore = false

[editor.gutters.line-numbers]
min-width = 1

[keys.normal]
j =   "move_char_left"
k =   "move_visual_line_down"
l =   "move_visual_line_up"
";" = "move_char_right"
h = "collapse_selection"
"A-h" = "flip_selections"

[keys.select]
j =   "extend_char_left"
k =   "extend_visual_line_down"
l =   "extend_visual_line_up"
";" = "extend_char_right"
h = "collapse_selection"
"A-h" = "flip_selections"
