#!/bin/sh

cons="$(nmcli -t -f NAME,TYPE connection show --active)"

IFS=$'\n'
for l in $cons; do
  echo $l
  IFS=':' read -r nname ntype <<< "$l"
  if [[ "$ntype" = "802-11-wireless" ]]; then
    IFS=':' read -r unused bars <<< "$(nmcli -t -f SSID,BARS device wifi list --rescan no | grep "$nname:")"
    printf "{ \"name\": \"$nname\", \"symbol\": \"\", \"signal\": \"$bars\" }\n"
    exit 1
  elif [[ "$ntype" = "802-3-ethernet" ]]; then
    printf "{ \"name\": \"$nname\", \"symbol\": \"󰱓\", \"signal\": \"\"  }\n"
    exit 1
  fi
done

printf "{ \"name\": \"Not Connected\", \"symbol\": \"\", \"signal\": \"\" }\n"
	
